version: "3.9"

services:
  app:
    build: .
    container_name: umbrella-video
    ports:
      - "8080:8080"
    volumes:
      - ./videos:/app/videos
    restart: unless-stopped

  app-gpu:
    build: .
    container_name: umbrella-video
    ports:
      - "8080:8080"
    volumes:
      - ./videos:/app/videos
    restart: unless-stopped

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    profiles:
      - gpu
